### ISSUE TITLE
Orgchart 3 -NDED or -DED is not optional argument for now

### ISSUE THREAD

**Issue by maybelinot** [kejbaly2/members#14]
Need to set -NDED as default or update readme and argparse

**Comment by maybelinot** [comment]
I do not understand for what purposes someones will need -NDED argument, for now it is only raises an error in the absence

**Comment by calmrat** [comment]
i don't see any error when I run with -NDED argument; in fact, it works as expected.

**Comment by maybelinot** [comment]
I have forgot to add DED in config file

**Comment by calmrat** [comment]
resolved.
