### ISSUE TITLE
HOOK: auto file TODO/FIXMEs as github issues

### ISSUE THREAD

**Issue by calmrat** [kejbaly2/members#3]

**Comment by calmrat** [comment]
eg, http://www.pythian.com/blog/pushing-your-code-todos-to-github-issues/ but with python... not perl, obviously. Keep searching, I'm sure there's an example out there somewhere...

**Comment by calmrat** [comment]
update in-line the comment pre-commit with comment + link to the issue

**Comment by maybelinot** [comment]
What do you think about :
https://github.com/jaidevd/pyticks/
https://github.com/Ricky54326/Github-Auto-Issue-Creator ?

**Comment by calmrat** [comment]
the solution with the hook displaying the FIXME's is sufficient for now.
